### ISSUE TITLE
Generate shorter sentences 

### ISSUE THREAD

**Issue by NarenZen** [mosaicml/llm-foundry#105]
I using mpt-intruct using hf.

I need to generate shorter sentences.
I'm using mpt-instruct for creating titles.

I need to restrict the length of the sentences.
what options are available?

I tried
length_penalty = -0.9 (but didn't work). Any suggested value for generating shorter sentences
Should i control the length using max_tokens or max_length.

I need to generate shorter sentences which will be used for creating titles/ headings.

**Comment by abhi-mosaic** [comment]
Hi @NarenZen , our MPT models are just HF causal language models, they don't have any special features for limiting generation beyond the utilities that HF provides: https://huggingface.co/docs/transformers/internal/generation_utils

I think using beam search together with `length_penalty` sounds like a good bet, but perhaps you need to use more aggressive settings or many beams? I would recommend asking the HF forums for advice.

Also just to double check, have you had success with coercing other HF models to produce short sentences? Because if there is a method that works for other HF models but not MPT, that would be a bug we can investigate.
