### ISSUE TITLE
MPT-7b models take very long to load (before actual model is loaded)

### ISSUE THREAD

**Issue by SinanAkkoyun** [mosaicml/llm-foundry#123]
Hello, the model takes very long to load for some reason. The actual shard loading is very fast but the delay before is several minutes on a 5950x and 3090

Is this to be expected?

**Comment by alextrott16** [comment]
Can't say for certain without knowing the details of what you're doing and the delays you're seeing, but in general, yes, this is to be expected.

**If training from scratch or loading from a Composer checkpoint** you can use `model.init_device: meta` to "meta" initialize, which is fast.

Otherwise, if starting from a HF checkpoint, loading the model involves first initializing the model on the CPU RAM, loading the weights into the model from disk (assuming they've already been downloaded), and then moving the model to GPU RAM. That process can add up to a few minutes and, I assume, accounts for the time you're seeing.
