### ISSUE TITLE
Triton not working on A40 and A6000 machines

### ISSUE THREAD

**Issue by NarenZen** [mosaicml/llm-foundry#190]
Installed following requirements:
PyTorch Version: 1.13.1
CUDA Version: 11.7
Python Version: 3.10
Ubuntu Version: 20.04

Inferencing is working fine. 
But when I train i get this error:
`RuntimeError: Triton Error [CUDA]: invalid argument`

GPU Device: A40

**Comment by pcardill0** [comment]
I've just found my issue when trying to train on an A10G and it may be related. These cards are sm86 and sm89 (compute capability) and fast-attention and seemingly Triton are limited to a head_dim of 64. I was able to get the small 125m and 360m models to train because they have a head_dim <=64. I was able to train larger models by increasing the number of heads to keep the head_dim=64. Also, setting  "attn_config: attn_impl: torch" seemed to work.

here is the issue discussed with respect to fast-attention: https://github.com/pytorch/pytorch/issues/100326

**Comment by tginart** [comment]
I also had this issue.

Triton flash attention is seems quite experimental & has issues in many environments.

**Comment by abhi-mosaic** [comment]
Closing this issue for now as I see a response in the PyTorch slack. In general we are focusing on making sure this repo works well on datacenter cards like A100, H100 and will try our best to make sure we provide fallback options (`attn_impl: torch`) that work on other cards. But we sadly don't have the bandwidth to optimize A40, A6000 ourselves right now :( 

The most probable path I see to Flash Attention on A40/A6000/others is `triton` gaining more adoption, more hardware coverage, and we will make sure to keep our `triton` codepath as up to date as possible.
