### ISSUE TITLE
eos tokens

### ISSUE THREAD

**Issue by tginart** [mosaicml/llm-foundry#199]
Not an issue, just a question.

Does llm-foundry automatically handle eos tokens or should we manually add them into our text data to denote?

For example, if we are loading in MDS data with a field `text:str`, should we manually make sure each sequence ends with the "<|endoftext|>" string?

Or is it sufficient to just leave it with:

```  # Tokenizer
  tokenizer:
    name: ${tokenizer_name}
    kwargs:
      pad_token: <|endoftext|>
      model_max_length: ${max_seq_len}
```

**Comment by alextrott16** [comment]
Oof sorry no one got around to answering this!

In the case you just described, it is recommended that you configure your tokenizer such that an EOS token is appended to the end of the token sequence when the `text:str` field is tokenized. I'm not sure that you can simply add a kwarg to the tokenizer to accomplish that. Some tokenizers (eg `gpt2`) do not add an EOS token (a lesson we learned the hard way a while ago).

Since you're using MDS data, I highly recommend that you pre-tokenize when converting to MDS. This will give you the opportunity to supply an EOS token, which will make sure that your tokenized sequences end with EOS. In `scripts/data_prep/` both the `convert_dataset_hf.py` and `convert_dataset_json.py` accept an `--eos_text` argument, which allows you to do what I was describing.

I'm going to close this on the hopes that I've answered your question. If I haven't, feel free to re-open.
