### ISSUE TITLE
Torch 1.13.1 doesn't support sm_90

### ISSUE THREAD

**Issue by jwatte** [mosaicml/llm-foundry#212]
Trying to use llm-foundry to finetune mpt-7b

The two kinds of GPUs I can get ahold of online are:
A10G -- not enough RAM to train mpt-7b
H100 -- uses sm_90, and the PyTorch 1.13.1 you recommend only works with sm_86 and below

What's the recommended path forward? A while back you suggested you were working on torch 2 support (or working around the triton problem in that version) -- is that available somewhere now?

**Comment by abhi-mosaic** [comment]
Hi @jwatte, we are actively working on torch2 support which should unlock H100s, CUDA 12.1 and ADA cards. I think you can try using the `main` branch today and it should mostly work (but you need to use Lion rather than AdamW due to this bug #221 ). You should expect a stable release v0.2.0 in a week or two.
