### ISSUE TITLE
Question: Does mpt-7b-instruct have the ability to understand Chinese?

### ISSUE THREAD

**Issue by Mewral** [mosaicml/llm-foundry#249]
Hi, I've tested mpt-7b-instruct and It does understand Chinese, but what confuses me is that the tokenizer that mpt-7b uses does not support Chinese, it's English only. So, how to understand this? Is this an ability of mpt-7b-instruct's zero-shot learning?

**Comment by jacobfulano** [comment]
While MPT-7B was mainly trained on English text, we have found that it is able to handle other languages such as Spanish and Portuguese. This is likely because these languages were included in some of the training data sources (for more details on the mixture of data sources we used, you might find this [twitter thread](https://twitter.com/leavittron/status/1657096163072565253) helpful).

The tokenizer used for MPT-7B is the GPT-NeoX-20B tokenizer, which was primarily trained on The Pile (see the GPT-NeoX paper [here](https://aclanthology.org/2022.bigscience-1.9.pdf)). While it is able to handle words/tokens in other languages including Chinese, its performance might not be as good for non-English languages as for English.

I would not say that this is necessarily a good example of zero-shot learning.
