### ISSUE TITLE
convert_composer_to_hf.py currently only supports MPT and not compatible with other models like llama

### ISSUE THREAD

**Issue by palash04** [mosaicml/llm-foundry#484]
I tried finetuning llama2 model (without lora). I needed to convert the saved composer checkpoint (.pt) to hf checkpoint folder. For that, if I use **convert_composer_to_hf.py**, it will obviously give error because of following:
```
 # register config auto class
MPTConfig.register_for_auto_class()

# register model auto class
MPTForCausalLM.register_for_auto_class('AutoModelForCausalLM')

print(f'Loading model from {local_folder_path}')
config = MPTConfig.from_pretrained(local_folder_path)
# You have to edit the config this way, because attn_config is a nested dictionary
config.attn_config['attn_impl'] = 'torch'
loaded_hf_model = MPTForCausalLM.from_pretrained(local_folder_path,
                                                 config=config,
                                                 torch_dtype=dtype)
```

Are there any plans to make changes to convert non MPT models?

**Comment by dakinggg** [comment]
Yeah, that script is specifically for MPT because we have custom code files that we need to edit to be compatible with the huggingface hub. For other models that are in `transformers` proper, please see https://github.com/mosaicml/llm-foundry/issues/139#issuecomment-1555426919 and https://github.com/mosaicml/examples/blob/main/examples/end-to-end-examples/sec_10k_qa/convert_composer_to_hf_transformers.py for a full script using that function.

**Comment by palash04** [comment]
Thanks @dakinggg. I am able to do inference now.
